"""Verify historical model weights generated by the modified upstream pipeline."""

from __future__ import annotations

import csv
import hashlib
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
REPRODUCTION = REPO / "artifacts" / "reproductions" / "upstream_pipeline"
MANIFEST = REPRODUCTION / "model_manifest.csv"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> int:
    with MANIFEST.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))

    errors: list[str] = []
    listed: set[Path] = set()
    for row in rows:
        path = (REPRODUCTION / row["file"]).resolve()
        listed.add(path)
        if row.get("provenance") != "local_modified_upstream_pipeline":
            errors.append(f"来源声明异常: {row['file']}")
        if row.get("source_data") != "upstream_author_mat":
            errors.append(f"源数据声明异常: {row['file']}")
        if row.get("git_added_commit") != "68a25c0":
            errors.append(f"Git 来源声明异常: {row['file']}")
        if row.get("usage") != "historical_reproduction_not_formal_baseline":
            errors.append(f"用途声明异常: {row['file']}")
        if not path.is_file():
            errors.append(f"文件不存在: {row['file']}")
            continue
        if path.stat().st_size != int(row["size_bytes"]):
            errors.append(f"大小变化: {row['file']}")
        if sha256(path) != row["sha256"].lower():
            errors.append(f"SHA-256 变化: {row['file']}")

    found = {path.resolve() for path in (REPRODUCTION / "models").glob("*.pth")}
    for path in sorted(found - listed):
        errors.append(f"未登记模型: {path.relative_to(REPRODUCTION)}")

    print(f"历史复现模型: manifest={len(rows)}, errors={len(errors)}")
    if errors:
        for error in errors:
            print(f"- {error}")
        return 1
    print("历史复现模型完整性检查通过；它们不是当前正式 baseline。")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
